### ISSUE TITLE
CORS issue with ui5-middleware-simpleproxy

### ISSUE THREAD

**Issue by DenisTis** [petermuessig/ui5-ecosystem-showcase#318]
Hi all, I am trying to use command "ui5 serve"
with the ui5-middleware-simpleproxy. Here is my ui5.yaml:

```
specVersion: "2.2"
type: application
metadata:
  name: CompanyRepo.appName
framework:
  name: SAPUI5
  version: 1.76.0
  libraries:
    - name: sap.ui.core
    - name: sap.m
    - name: sap.ui.comp
    - name: sap.ushell
    - name: themelib_sap_fiori_3
server:
  customMiddleware:
    - name: ui5-middleware-simpleproxy
      afterMiddleware: compression
      mountPath: /northwind
      configuration:
        baseUri: "http://services.odata.org/Northwind/Northwind.svc/"
        strictSSL: true

```
This is my controller code, which loads the model:
```
    return Controller.extend("companyRepo.appName.controller.App", {
      onInit: function() {
        var me = this;
        me.getView().setBusy(true);
        var oModel = new sap.ui.model.odata.v2.ODataModel({
          serviceUrl: "/northwind",
        });
        oModel.metadataLoaded().then(function(oEvent) {
          console.log(oEvent);
          me.getView().setModel(oModel, "NorthwindModel");
          me.getView().setBusy(false);
        });
      },
    });

```

However, once I try to load model I get error: 
`Access to XMLHttpRequest at 'https://services.odata.org/Northwind/Northwind.svc/$metadata' (redirected from 'http://localhost:8080/northwind/$metadata') from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

Am I doing something wrong?
