### ISSUE TITLE
'keepResources' flag doesn't seem to work?

### ISSUE THREAD

**Issue by jbm1991** [petermuessig/ui5-ecosystem-showcase#441]
Hi,

Even though I have specified `keepResources: false` in the ui5.yaml configuration, the resources are still included in the zip file. I've tried setting it to true/false and removing it all together but it appears to be always ignored.

ui5-task-zipper: 0.4.1
@ui5/cli: 2.7.1

ui5.yaml
```
specVersion: "2.2"
metadata:
  name: example.app
type: application
resources:
  configuration:
    paths:
      webapp: webapp
framework:
  name: SAPUI5
  version: 1.84.3
  libraries:
    - name: sap.m
    - name: sap.ui.core
    - name: sap.ui.layout
    - name: sap.ushell
      development: true
    - name: themelib_sap_fiori_3
server:
  customMiddleware:
    - name: ui5-middleware-livereload
      afterMiddleware: compression
      configuration:
        port: 35729
        path: webapp
    - name: ui5-middleware-simpleproxy
      mountPath: /v2/example
      afterMiddleware: compression
      configuration:
        baseUri: http://localhost:4004/v2/example
builder:
  resources:
    excludes:
      - "/test/**"
      - "/test-resources/**"
  customTasks:
    - name: "ui5-task-zipper"
      afterTask: "uglify"
      configuration:
        archiveName: "exampleui"
        keepResources: false
```
